### PR TITLE
Retrieved weather and displayed on each park

### PR DESCRIPTION
**Pull request by tun24709**
Each park now has info about their weather on the bottom left of the page.

current weather

### CODE REVIEW

**Review by jonathan-d-zhang — CHANGES_REQUESTED** [review]
Looks good (I don't know anything about React :shipit:). But are we sure that it is almost 300F at this park?

**Comment by tun24709** [comment]
I will have to recheck that, I think I may have pulled the wrong data

**Comment by jonathan-d-zhang** [comment]
I would guess that it is being returned in Kelvin

**Comment by tun24709** [comment]
Thanks! I changed it so that the units are in degrees F, it was returning in Kelvin

**Review by jonathan-d-zhang — APPROVED** [review]
🎉

**Pull request merged**
